// ═══════════════════════════════════════════════════════
//  UNITED STATES OF GIT — Mock Data
//  Provides demo data so the app renders without API key
// ═══════════════════════════════════════════════════════

import { RepoData, getLanguageColor } from './types';

const MOCK_REPOS: RepoData[] = [
  {
    id: '1', name: 'linux', fullName: 'torvalds/linux',
    description: 'Linux kernel source tree',
    url: 'https://github.com/torvalds/linux', homepage: null,
    stars: 185000, forks: 55000, watchers: 185000, openIssues: 350, contributors: 4800,
    language: 'C', languages: [{ name: 'C', percentage: 97.5, color: getLanguageColor('C') }, { name: 'Assembly', percentage: 1.2, color: '#6E4C13' }],
    topics: ['linux', 'kernel', 'os'], license: 'GPL-2.0',
    createdAt: '2011-09-04T22:48:12Z', updatedAt: '2026-03-04T00:00:00Z', pushedAt: '2026-03-04T00:00:00Z',
    owner: { login: 'torvalds', avatarUrl: 'https://avatars.githubusercontent.com/u/1024025', type: 'User', url: 'https://github.com/torvalds', location: 'Portland, OR' },
    location: { lat: 45.5152, lng: -122.6784, city: 'Portland', country: 'United States', countryCode: 'US' },
    isArchived: false, isFork: false, defaultBranch: 'master', size: 4500000,
    towerHeight: 14, glowIntensity: 0.93, recentActivity: 'blazing',
  },
  {
    id: '2', name: 'react', fullName: 'facebook/react',
    description: 'The library for web and native user interfaces',
    url: 'https://github.com/facebook/react', homepage: 'https://react.dev',
    stars: 230000, forks: 47000, watchers: 230000, openIssues: 900, contributors: 1800,
    language: 'JavaScript', languages: [{ name: 'JavaScript', percentage: 78, color: getLanguageColor('JavaScript') }, { name: 'TypeScript', percentage: 18, color: getLanguageColor('TypeScript') }],
    topics: ['react', 'javascript', 'ui', 'frontend'], license: 'MIT',
    createdAt: '2013-05-24T16:15:54Z', updatedAt: '2026-03-04T00:00:00Z', pushedAt: '2026-03-04T00:00:00Z',
    owner: { login: 'facebook', avatarUrl: 'https://avatars.githubusercontent.com/u/69631', type: 'Organization', url: 'https://github.com/facebook', location: 'Menlo Park, CA' },
    location: { lat: 37.4530, lng: -122.1817, city: 'Menlo Park', country: 'United States', countryCode: 'US' },
    isArchived: false, isFork: false, defaultBranch: 'main', size: 320000,
    towerHeight: 15, glowIntensity: 1.0, recentActivity: 'blazing',
  },
  {
    id: '3', name: 'tensorflow', fullName: 'tensorflow/tensorflow',
    description: 'An open source machine learning framework',
    url: 'https://github.com/tensorflow/tensorflow', homepage: 'https://tensorflow.org',
    stars: 190000, forks: 74000, watchers: 190000, openIssues: 2100, contributors: 3500,
    language: 'C++', languages: [{ name: 'C++', percentage: 62, color: getLanguageColor('C++') }, { name: 'Python', percentage: 28, color: getLanguageColor('Python') }],
    topics: ['machine-learning', 'deep-learning', 'ai', 'tensorflow'], license: 'Apache-2.0',
    createdAt: '2015-11-07T01:19:20Z', updatedAt: '2026-03-04T00:00:00Z', pushedAt: '2026-03-03T00:00:00Z',
    owner: { login: 'tensorflow', avatarUrl: 'https://avatars.githubusercontent.com/u/15658638', type: 'Organization', url: 'https://github.com/tensorflow', location: 'Mountain View, CA' },
    location: { lat: 37.3861, lng: -122.0839, city: 'Mountain View', country: 'United States', countryCode: 'US' },
    isArchived: false, isFork: false, defaultBranch: 'master', size: 620000,
    towerHeight: 14.5, glowIntensity: 0.96, recentActivity: 'active',
  },
  {
    id: '4', name: 'vscode', fullName: 'microsoft/vscode',
    description: 'Visual Studio Code',
    url: 'https://github.com/microsoft/vscode', homepage: 'https://code.visualstudio.com',
    stars: 170000, forks: 31000, watchers: 170000, openIssues: 8000, contributors: 2100,
    language: 'TypeScript', languages: [{ name: 'TypeScript', percentage: 93, color: getLanguageColor('TypeScript') }],
    topics: ['editor', 'ide', 'typescript', 'electron'], license: 'MIT',
    createdAt: '2015-09-03T20:23:38Z', updatedAt: '2026-03-04T00:00:00Z', pushedAt: '2026-03-04T00:00:00Z',
    owner: { login: 'microsoft', avatarUrl: 'https://avatars.githubusercontent.com/u/6154722', type: 'Organization', url: 'https://github.com/microsoft', location: 'Redmond, WA' },
    location: { lat: 47.6740, lng: -122.1215, city: 'Redmond', country: 'United States', countryCode: 'US' },
    isArchived: false, isFork: false, defaultBranch: 'main', size: 510000,
    towerHeight: 13.5, glowIntensity: 0.90, recentActivity: 'blazing',
  },
  {
    id: '5', name: 'next.js', fullName: 'vercel/next.js',
    description: 'The React Framework',
    url: 'https://github.com/vercel/next.js', homepage: 'https://nextjs.org',
    stars: 130000, forks: 28000, watchers: 130000, openIssues: 3200, contributors: 3200,
    language: 'JavaScript', languages: [{ name: 'JavaScript', percentage: 45, color: getLanguageColor('JavaScript') }, { name: 'TypeScript', percentage: 48, color: getLanguageColor('TypeScript') }],
    topics: ['nextjs', 'react', 'framework', 'ssr'], license: 'MIT',
    createdAt: '2016-10-05T23:32:51Z', updatedAt: '2026-03-04T00:00:00Z', pushedAt: '2026-03-04T00:00:00Z',
    owner: { login: 'vercel', avatarUrl: 'https://avatars.githubusercontent.com/u/14985020', type: 'Organization', url: 'https://github.com/vercel', location: 'San Francisco' },
    location: { lat: 37.7749, lng: -122.4194, city: 'San Francisco', country: 'United States', countryCode: 'US' },
    isArchived: false, isFork: false, defaultBranch: 'canary', size: 890000,
    towerHeight: 13, glowIntensity: 0.87, recentActivity: 'blazing',
  },
  {
    id: '6', name: 'rust', fullName: 'rust-lang/rust',
    description: 'Empowering everyone to build reliable and efficient software',
    url: 'https://github.com/rust-lang/rust', homepage: 'https://rust-lang.org',
    stars: 100000, forks: 13000, watchers: 100000, openIssues: 9500, contributors: 5000,
    language: 'Rust', languages: [{ name: 'Rust', percentage: 95, color: getLanguageColor('Rust') }],
    topics: ['rust', 'compiler', 'systems-programming'], license: 'MIT',
    createdAt: '2010-06-16T20:39:03Z', updatedAt: '2026-03-04T00:00:00Z', pushedAt: '2026-03-04T00:00:00Z',
    owner: { login: 'rust-lang', avatarUrl: 'https://avatars.githubusercontent.com/u/5430905', type: 'Organization', url: 'https://github.com/rust-lang', location: null },
    location: { lat: 37.7749, lng: -122.2, city: 'San Francisco', country: 'United States', countryCode: 'US' },
    isArchived: false, isFork: false, defaultBranch: 'master', size: 720000,
    towerHeight: 13.2, glowIntensity: 0.88, recentActivity: 'blazing',
  },
  {
    id: '7', name: 'kubernetes', fullName: 'kubernetes/kubernetes',
    description: 'Production-Grade Container Orchestration',
    url: 'https://github.com/kubernetes/kubernetes', homepage: 'https://kubernetes.io',
    stars: 115000, forks: 40000, watchers: 115000, openIssues: 2500, contributors: 3800,
    language: 'Go', languages: [{ name: 'Go', percentage: 96, color: getLanguageColor('Go') }],
    topics: ['kubernetes', 'containers', 'devops', 'cloud-native'], license: 'Apache-2.0',
    createdAt: '2014-06-06T22:56:04Z', updatedAt: '2026-03-04T00:00:00Z', pushedAt: '2026-03-04T00:00:00Z',
    owner: { login: 'kubernetes', avatarUrl: 'https://avatars.githubusercontent.com/u/13629408', type: 'Organization', url: 'https://github.com/kubernetes', location: null },
    location: { lat: 47.6062, lng: -122.3321, city: 'Seattle', country: 'United States', countryCode: 'US' },
    isArchived: false, isFork: false, defaultBranch: 'master', size: 810000,
    towerHeight: 13.8, glowIntensity: 0.92, recentActivity: 'blazing',
  },
  {
    id: '8', name: 'flutter', fullName: 'flutter/flutter',
    description: 'Flutter makes it easy to build apps for mobile, web, and desktop',
    url: 'https://github.com/flutter/flutter', homepage: 'https://flutter.dev',
    stars: 168000, forks: 28000, watchers: 168000, openIssues: 12000, contributors: 1300,
    language: 'Dart', languages: [{ name: 'Dart', percentage: 91, color: getLanguageColor('Dart') }],
    topics: ['flutter', 'dart', 'mobile', 'cross-platform'], license: 'BSD-3-Clause',
    createdAt: '2015-03-06T22:54:58Z', updatedAt: '2026-03-04T00:00:00Z', pushedAt: '2026-03-04T00:00:00Z',
    owner: { login: 'flutter', avatarUrl: 'https://avatars.githubusercontent.com/u/14101776', type: 'Organization', url: 'https://github.com/flutter', location: 'Mountain View, CA' },
    location: { lat: 37.39, lng: -122.09, city: 'Mountain View', country: 'United States', countryCode: 'US' },
    isArchived: false, isFork: false, defaultBranch: 'master', size: 350000,
    towerHeight: 13.3, glowIntensity: 0.89, recentActivity: 'blazing',
  },
  {
    id: '9', name: 'vue', fullName: 'vuejs/core',
    description: 'The Progressive JavaScript Framework',
    url: 'https://github.com/vuejs/core', homepage: 'https://vuejs.org',
    stars: 215000, forks: 35000, watchers: 215000, openIssues: 500, contributors: 450,
    language: 'TypeScript', languages: [{ name: 'TypeScript', percentage: 88, color: getLanguageColor('TypeScript') }],
    topics: ['vue', 'javascript', 'framework', 'frontend'], license: 'MIT',
    createdAt: '2013-07-29T03:24:51Z', updatedAt: '2026-03-03T00:00:00Z', pushedAt: '2026-03-03T00:00:00Z',
    owner: { login: 'vuejs', avatarUrl: 'https://avatars.githubusercontent.com/u/6128107', type: 'Organization', url: 'https://github.com/vuejs', location: null },
    location: { lat: 40.7128, lng: -74.0060, city: 'New York', country: 'United States', countryCode: 'US' },
    isArchived: false, isFork: false, defaultBranch: 'main', size: 42000,
    towerHeight: 12.8, glowIntensity: 0.85, recentActivity: 'active',
  },
  {
    id: '10', name: 'deno', fullName: 'denoland/deno',
    description: 'A modern runtime for JavaScript and TypeScript',
    url: 'https://github.com/denoland/deno', homepage: 'https://deno.land',
    stars: 98000, forks: 5400, watchers: 98000, openIssues: 1500, contributors: 900,
    language: 'Rust', languages: [{ name: 'Rust', percentage: 68, color: getLanguageColor('Rust') }, { name: 'JavaScript', percentage: 22, color: getLanguageColor('JavaScript') }],
    topics: ['deno', 'runtime', 'typescript', 'rust'], license: 'MIT',
    createdAt: '2018-05-14T02:55:54Z', updatedAt: '2026-03-04T00:00:00Z', pushedAt: '2026-03-04T00:00:00Z',
    owner: { login: 'denoland', avatarUrl: 'https://avatars.githubusercontent.com/u/42048915', type: 'Organization', url: 'https://github.com/denoland', location: null },
    location: { lat: 51.5074, lng: -0.1278, city: 'London', country: 'United Kingdom', countryCode: 'GB' },
    isArchived: false, isFork: false, defaultBranch: 'main', size: 95000,
    towerHeight: 12.2, glowIntensity: 0.81, recentActivity: 'blazing',
  },
  {
    id: '11', name: 'pytorch', fullName: 'pytorch/pytorch',
    description: 'Tensors and Dynamic neural networks in Python',
    url: 'https://github.com/pytorch/pytorch', homepage: 'https://pytorch.org',
    stars: 87000, forks: 23000, watchers: 87000, openIssues: 14000, contributors: 3700,
    language: 'Python', languages: [{ name: 'Python', percentage: 52, color: getLanguageColor('Python') }, { name: 'C++', percentage: 38, color: getLanguageColor('C++') }],
    topics: ['pytorch', 'deep-learning', 'machine-learning', 'python'], license: 'BSD-3-Clause',
    createdAt: '2016-08-13T02:11:47Z', updatedAt: '2026-03-04T00:00:00Z', pushedAt: '2026-03-04T00:00:00Z',
    owner: { login: 'pytorch', avatarUrl: 'https://avatars.githubusercontent.com/u/21003710', type: 'Organization', url: 'https://github.com/pytorch', location: 'Menlo Park, CA' },
    location: { lat: 37.46, lng: -122.18, city: 'Menlo Park', country: 'United States', countryCode: 'US' },
    isArchived: false, isFork: false, defaultBranch: 'main', size: 1100000,
    towerHeight: 13.6, glowIntensity: 0.91, recentActivity: 'blazing',
  },
  {
    id: '12', name: 'Django', fullName: 'django/django',
    description: 'The Web framework for perfectionists with deadlines',
    url: 'https://github.com/django/django', homepage: 'https://djangoproject.com',
    stars: 82000, forks: 32000, watchers: 82000, openIssues: 200, contributors: 2700,
    language: 'Python', languages: [{ name: 'Python', percentage: 97, color: getLanguageColor('Python') }],
    topics: ['python', 'django', 'web-framework'], license: 'BSD-3-Clause',
    createdAt: '2012-04-28T02:47:18Z', updatedAt: '2026-03-04T00:00:00Z', pushedAt: '2026-03-04T00:00:00Z',
    owner: { login: 'django', avatarUrl: 'https://avatars.githubusercontent.com/u/27804', type: 'Organization', url: 'https://github.com/django', location: null },
    location: { lat: 52.3676, lng: 4.9041, city: 'Amsterdam', country: 'Netherlands', countryCode: 'NL' },
    isArchived: false, isFork: false, defaultBranch: 'main', size: 350000,
    towerHeight: 12.6, glowIntensity: 0.84, recentActivity: 'active',
  },
  {
    id: '13', name: 'rails', fullName: 'rails/rails',
    description: 'Ruby on Rails',
    url: 'https://github.com/rails/rails', homepage: 'https://rubyonrails.org',
    stars: 56000, forks: 22000, watchers: 56000, openIssues: 600, contributors: 5000,
    language: 'Ruby', languages: [{ name: 'Ruby', percentage: 95, color: getLanguageColor('Ruby') }],
    topics: ['ruby', 'rails', 'web-framework', 'mvc'], license: 'MIT',
    createdAt: '2008-04-11T02:19:47Z', updatedAt: '2026-03-04T00:00:00Z', pushedAt: '2026-03-04T00:00:00Z',
    owner: { login: 'rails', avatarUrl: 'https://avatars.githubusercontent.com/u/4223', type: 'Organization', url: 'https://github.com/rails', location: null },
    location: { lat: 52.52, lng: 13.405, city: 'Berlin', country: 'Germany', countryCode: 'DE' },
    isArchived: false, isFork: false, defaultBranch: 'main', size: 260000,
    towerHeight: 12.8, glowIntensity: 0.85, recentActivity: 'active',
  },
  {
    id: '14', name: 'swift', fullName: 'apple/swift',
    description: 'The Swift Programming Language',
    url: 'https://github.com/apple/swift', homepage: 'https://swift.org',
    stars: 68000, forks: 10000, watchers: 68000, openIssues: 7500, contributors: 1100,
    language: 'C++', languages: [{ name: 'C++', percentage: 55, color: getLanguageColor('C++') }, { name: 'Swift', percentage: 35, color: getLanguageColor('Swift') }],
    topics: ['swift', 'compiler', 'programming-language', 'apple'], license: 'Apache-2.0',
    createdAt: '2015-10-23T21:15:07Z', updatedAt: '2026-03-04T00:00:00Z', pushedAt: '2026-03-04T00:00:00Z',
    owner: { login: 'apple', avatarUrl: 'https://avatars.githubusercontent.com/u/10639145', type: 'Organization', url: 'https://github.com/apple', location: null },
    location: { lat: 37.3318, lng: -122.0312, city: 'Cupertino', country: 'United States', countryCode: 'US' },
    isArchived: false, isFork: false, defaultBranch: 'main', size: 980000,
    towerHeight: 12.1, glowIntensity: 0.81, recentActivity: 'blazing',
  },
  {
    id: '15', name: 'svelte', fullName: 'sveltejs/svelte',
    description: 'Cybernetically enhanced web apps',
    url: 'https://github.com/sveltejs/svelte', homepage: 'https://svelte.dev',
    stars: 81000, forks: 4300, watchers: 81000, openIssues: 800, contributors: 580,
    language: 'JavaScript', languages: [{ name: 'JavaScript', percentage: 65, color: getLanguageColor('JavaScript') }, { name: 'TypeScript', percentage: 30, color: getLanguageColor('TypeScript') }],
    topics: ['svelte', 'compiler', 'ui', 'framework'], license: 'MIT',
    createdAt: '2016-11-20T18:41:33Z', updatedAt: '2026-03-04T00:00:00Z', pushedAt: '2026-03-04T00:00:00Z',
    owner: { login: 'sveltejs', avatarUrl: 'https://avatars.githubusercontent.com/u/23617963', type: 'Organization', url: 'https://github.com/sveltejs', location: null },
    location: { lat: 51.5074, lng: 0.1, city: 'London', country: 'United Kingdom', countryCode: 'GB' },
    isArchived: false, isFork: false, defaultBranch: 'main', size: 14000,
    towerHeight: 11.2, glowIntensity: 0.75, recentActivity: 'active',
  },
  {
    id: '16', name: 'godot', fullName: 'godotengine/godot',
    description: 'Godot Engine – Multi-platform 2D and 3D game engine',
    url: 'https://github.com/godotengine/godot', homepage: 'https://godotengine.org',
    stars: 94000, forks: 21000, watchers: 94000, openIssues: 13000, contributors: 2300,
    language: 'C++', languages: [{ name: 'C++', percentage: 88, color: getLanguageColor('C++') }],
    topics: ['game-engine', 'godot', 'gamedev', '3d', '2d'], license: 'MIT',
    createdAt: '2014-01-01T05:24:00Z', updatedAt: '2026-03-04T00:00:00Z', pushedAt: '2026-03-04T00:00:00Z',
    owner: { login: 'godotengine', avatarUrl: 'https://avatars.githubusercontent.com/u/6318174', type: 'Organization', url: 'https://github.com/godotengine', location: null },
    location: { lat: -34.6037, lng: -58.3816, city: 'Buenos Aires', country: 'Argentina', countryCode: 'AR' },
    isArchived: false, isFork: false, defaultBranch: 'master', size: 1400000,
    towerHeight: 13.1, glowIntensity: 0.87, recentActivity: 'blazing',
  },
  {
    id: '17', name: 'ansible', fullName: 'ansible/ansible',
    description: 'Ansible is a radically simple IT automation platform',
    url: 'https://github.com/ansible/ansible', homepage: 'https://ansible.com',
    stars: 63000, forks: 24000, watchers: 63000, openIssues: 800, contributors: 5400,
    language: 'Python', languages: [{ name: 'Python', percentage: 96, color: getLanguageColor('Python') }],
    topics: ['ansible', 'devops', 'automation', 'infrastructure'], license: 'GPL-3.0',
    createdAt: '2012-03-06T14:58:02Z', updatedAt: '2026-03-04T00:00:00Z', pushedAt: '2026-03-03T00:00:00Z',
    owner: { login: 'ansible', avatarUrl: 'https://avatars.githubusercontent.com/u/1507452', type: 'Organization', url: 'https://github.com/ansible', location: null },
    location: { lat: 35.6762, lng: 139.6503, city: 'Tokyo', country: 'Japan', countryCode: 'JP' },
    isArchived: false, isFork: false, defaultBranch: 'devel', size: 190000,
    towerHeight: 12.9, glowIntensity: 0.86, recentActivity: 'active',
  },
  {
    id: '18', name: 'electron', fullName: 'electron/electron',
    description: 'Build cross-platform desktop apps with JavaScript, HTML, and CSS',
    url: 'https://github.com/electron/electron', homepage: 'https://electronjs.org',
    stars: 115000, forks: 16000, watchers: 115000, openIssues: 1000, contributors: 1200,
    language: 'C++', languages: [{ name: 'C++', percentage: 52, color: getLanguageColor('C++') }, { name: 'TypeScript', percentage: 30, color: getLanguageColor('TypeScript') }],
    topics: ['electron', 'desktop', 'javascript', 'chromium'], license: 'MIT',
    createdAt: '2013-04-12T01:47:36Z', updatedAt: '2026-03-04T00:00:00Z', pushedAt: '2026-03-04T00:00:00Z',
    owner: { login: 'electron', avatarUrl: 'https://avatars.githubusercontent.com/u/13409222', type: 'Organization', url: 'https://github.com/electron', location: 'San Francisco' },
    location: { lat: 37.78, lng: -122.42, city: 'San Francisco', country: 'United States', countryCode: 'US' },
    isArchived: false, isFork: false, defaultBranch: 'main', size: 120000,
    towerHeight: 12.4, glowIntensity: 0.83, recentActivity: 'blazing',
  },
];

export function getMockRepos(): RepoData[] {
  return MOCK_REPOS;
}

export function getMockRepoById(id: string): RepoData | null {
  return MOCK_REPOS.find(r => r.id === id) || null;
}
